CREATE TABLE author
(
    id         BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name VARCHAR(20),
    last_name  VARCHAR(20)
);

CREATE TABLE genre
(
    id    BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title VARCHAR(20)
);

CREATE TABLE book
(
    id          BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(256),
    description VARCHAR(2048),
    author_id   BIGINT references author(id),
    genre_id    BIGINT references genre(id),
    price       DOUBLE PRECISION                        NOT NULL
);

CREATE TABLE category
(
    id    BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title VARCHAR(20)
);

CREATE TABLE book_category(
    book_id BIGINT REFERENCES book(id),
    category_id BIGINT REFERENCES category(id),
    PRIMARY KEY (book_id, category_id)
);

CREATE TABLE bucket_book
(
    book_id BIGINT REFERENCES book(id),
    bucket_id BIGINT REFERENCES bucket(id),
    PRIMARY KEY (book_id, bucket_id)
);

CREATE TABLE "user"
(
    id              BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username        VARCHAR(255) NOT NULL ,
    password        VARCHAR(255) NOT NULL ,
    active          BOOLEAN                                 NOT NULL,
    email           VARCHAR(255) UNIQUE NOT NULL ,
    activation_code VARCHAR(255),
    role            VARCHAR(255)
);

CREATE TABLE receipt
(
    id          BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description VARCHAR(255),
    created     TIMESTAMP WITHOUT TIME ZONE,
    updated     TIMESTAMP WITHOUT TIME ZONE,
    user_id     BIGINT references "user"(id),
    sum         DOUBLE PRECISION                        NOT NULL,
    address     VARCHAR(200),
    status      VARCHAR(255)
);

CREATE TABLE receipt_detail
(
    id         BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    receipt_id BIGINT references receipt(id),
    book_id    BIGINT references book(id),
    amount     INTEGER                                 NOT NULL,
    price      DOUBLE PRECISION                        NOT NULL
);

CREATE TABLE bucket
(
    id      BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id BIGINT references "user"(id)
);

CREATE TABLE user_book(
    user_id BIGINT REFERENCES "user"(id),
    book_id BIGINT REFERENCES book(id),
    PRIMARY KEY (user_id, book_id)
);